# Parts of Speech

## Exploring Changing Sentiment in Climate Articles: 2013 to 2023

#### This notebook builds F2 and F3 level models from the corpus.

#### Written by Rafael Alvarado(1) and Caroline Kranefuss(1).

(1) University of Virginia, 2026

## Imports

In [1]:
# General imports
import pandas as pd 
import numpy as np 
import os
import sys

# Plotting
import matplotlib.pyplot as plt
import seaborn as sns

# Project-specific imports
import glob
from lxml import etree
from glob import glob
import re
import nltk
nltk_resources = [
    'tokenizers/punkt', 
    'averaged_perceptron_tagger_eng',
    'corpora/stopwords', 
    'help/tagsets'
]

for resource in nltk_resources:
    try:
        nltk.data.find(resource)
    except LookupError:
        nltk.download(resource)
        
        
# ----File Stitching----
# If not in repo home folder, cd back 
if os.path.basename(os.getcwd()) != "evolving_sentiment_climate":
    os.chdir('..')
# If a file is in /sources/, access it by telling the system to look at that path as well as current path
sys.path.append(os.path.join(os.getcwd(), '..', 'sources'))
source_dir = "sources"
source_files_paths = glob(f"{source_dir}/*.xml")

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\student\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [2]:
%%capture
%run notebooks/eda.ipynb

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\student\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [3]:
VOCAB

                  n         p      p_yr
year term_str
2013 the       3045  0.016252  0.063549
     of        1810  0.009661  0.037774
     and       1433  0.007649  0.029907
     in        1206  0.006437  0.025169
     to         967  0.005161  0.020181
...             ...       ...       ...
2023 consoles     1  0.000005  0.000013
     opt          1  0.000005  0.000013
     azure        1  0.000005  0.000013
     console      1  0.000005  0.000013
     xbox         1  0.000005  0.000013

[21582 rows x 3 columns]

In [4]:
VOCAB['n_pos_group'] = CORPUS[['term_str','pos_group']].value_counts().unstack().count(1)
VOCAB['cat_pos_group'] = CORPUS[['term_str','pos_group']].value_counts().to_frame('n').reset_index()\
    .groupby('term_str').pos_group.apply(lambda x: set(x))
VOCAB['n_pos'] = CORPUS[['term_str','pos']].value_counts().unstack().count(1)
VOCAB['cat_pos'] = CORPUS[['term_str','pos']].value_counts().to_frame('n').reset_index()\
    .groupby('term_str').pos.apply(lambda x: set(x))

VOCAB.head()

                  n         p      p_yr  n_pos_group cat_pos_group  n_pos  \
year term_str
2013 the       3045  0.016252  0.063549            1          {DT}      1
     of        1810  0.009661  0.037774            1          {IN}      1
     and       1433  0.007649  0.029907            2      {NN, CC}      2
     in        1206  0.006437  0.025169            2      {NN, IN}      2
     to         967  0.005161  0.020181            1          {TO}      1

                 cat_pos
year term_str
2013 the            {DT}
     of             {IN}
     and       {NNP, CC}
     in        {NNP, IN}
     to             {TO}